sudo: required
services:
  - docker


before_install:
  - docker build -t csmajer/docker-react-3 -f Dockerfile.dev .

script:
  - docker run -e CI=true csmajer/docker-react-3 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-532309044952"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"